### ISSUE TITLE
broom: tidyer removed with version 0.7.3

### ISSUE THREAD

**Issue by MatthieuStigler** [sgaure/lfe#45]
As per broom news (https://cran.r-project.org/web/packages/broom/news/news.html), tidyr were removed at 0.7.3. Should ask if okay to put back, although they seem to rather want to have tidyers in own package!? (https://github.com/tidymodels/broom/issues/777 and https://github.com/tidymodels/broom/issues/795#issuecomment-639547477)?

**Comment by tappek** [comment]
broom version 0.7.4 added back the tidiers for felm/lfe. I found the immediate removal of tidiers when lfe was archied a bit overzealous.
