### ISSUE TITLE
lfe and R-devel

### ISSUE THREAD

**Issue by SebKrantz** [sgaure/lfe#49]
Hi @MatthieuStigler, I found some background reading on reference counting which is a new lfe issue on R-devel: https://developer.r-project.org/Refcnt.html. It seems this has been depreciated. 
I think putting something like 

```
#ifdef COMPUTE_REFCNT_VALUES
#undef COMPUTE_REFCNT_VALUES
```
and getting rid of all the REFCNT and SET_REFCNT expressions in utils.c could solve the issue.

**Comment by SebKrantz** [comment]
Actually these are things he added in this commit: https://github.com/sgaure/lfe/commit/cd7333faf0dec1c8a2a47f38e0e6f789d44687ea, sou you could also just reverse all changes committed here.

**Comment by MatthieuStigler** [comment]
Hi @SebKrantz 

Thanks for your message, this is extremely useful! Indeed, I received previously a message by Luke Thierney, mentionning this, but I have to admit I was totally confused about it! Luke's message was: 

> We are working on rearranging our header files with the goal of making the installed headers correspond more closely to the API available to packages.  I expect to commit the initial changes next week. The current new version of Rinternals.h is available here: https://www.stat.uiowa.edu/~luke/R/API
> 
> The corresponding Defn.h needed for building R is in there as well.
> 
> Your package lfe will fail in R-devel once this change is committed:
> 
> SET_REFCNT is not in the API so you should not use it.

This seems to correspond to your diagnostic? As this goes well beyond my understanding, is there any chance you could submit a pull request with your suggested changes?

Thanks A TON!!

**Comment by SebKrantz** [comment]
Hi Matthieu,

So I also have limited understanding of this, but what is happening is that
R core is restructuring header files in the C API and removing functions
not intended for use by packages. SET_REFCNT Is one of those functions to
be removed. In this case, since he added this using one commit I think the
solution could simply be to reverse in full (perhaps exempting the
additions to .gitignore)
the commit I have flagged to you which he used to add this. So reverse
those changes in the current version you have (don’t need to reverse all
later changes, just make a new commit that reverses this one except for
.gitignore) and run R CMD Check. If it doesn’t work I am happy to look
further into it.

**Comment by MatthieuStigler** [comment]
Oh great, I just reverted the commit you suggested, a win-builder test on R-devel gave no error, while the previous one gave a ton! I will then prepare a new version with this revert, thanks @SebKrantz

**Comment by tappek** [comment]
Great to hear. I think the current CRAN version 2.8-6 has a typo in its news file:
"Package is archived from CRAN and temporarily adopted by Matthieu Stigler."
I think it should read "_un_archived"? If so, you might want to change this for the next release.

**Comment by MatthieuStigler** [comment]
ok, version 2.8-7 was accepted on CRAN, fixing the issue thanks to @SebKrantz, thanks again!! Want to close the issue?

And well spotted @tappek , thanks!

**Comment by SebKrantz** [comment]
Ok, great, well done!
